application: bucket-lister
version: 1
runtime: python27
threadsafe: yes
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest
