application: bucket_lister
version: 1
runtime: python27
threadsafe: no
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /listing.xsl
  static_files: listing.xsl
  upload: listing.xsl

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: .*
  script: main.py
